# Generated by Django 5.2.4 on 2025-07-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_birth_date_user_location_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
