from . import views
from django.urls import path

urlpatterns = [
    path('overview/', views.view_overview, name='view_overview'),
    path('my-tasks/', views.my_tasks_view, name='my_tasks'),
    path('projects/', views.view_projects, name='view_projects'),
    path('projects/create/', views.create_project, name='create_project'),
    path('projects/<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path('projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('projects/<int:project_id>/', views.view_project_detail, name='view_project_detail'),
    path('projects/<int:project_id>/tasks/create/', views.create_task, name='create_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.view_project_task_id, name='view_project_task_id'),
    path('projects/<int:project_id>/tasks/<int:task_id>/update/', views.update_task, name='update_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/comments/', views.create_comment, name='create_comment'),
    path('projects/<int:project_id>/members/', views.view_project_members, name='view_project_members'),
    path('projects/<int:project_id>/members/invite/', views.invite_member, name='invite_member'),
    path('projects/<int:project_id>/members/<int:member_id>/remove/', views.remove_member, name='remove_member'),
    path('projects/<int:project_id>/members/<int:member_id>/update-role/', views.update_member_role, name='update_member_role'),
    path('projects/<int:project_id>/invitations/<int:invitation_id>/cancel/', views.cancel_invitation, name='cancel_invitation'),
    path('invitations/<int:invitation_id>/accept/', views.accept_invitation, name='accept_invitation'),
    path('invitations/<int:invitation_id>/decline/', views.decline_invitation, name='decline_invitation'),
    path('members/', views.view_all_members, name='view_all_members'),
    path('frame/', views.view_frame, name='view_frame'),
    path('settings/', views.view_settings, name='view_settings'),
    path('personal/', views.view_profile, name='view_profile'),
    path('personal/update/', views.update_profile, name='update_profile'),
    path('personal/change-password/', views.change_password, name='change_password'),
    path('search/', views.search_view, name='search'),
    path('statistics/tasks/', views.task_statistics_view, name='task_statistics'),
    path('api/statistics/tasks/', views.task_statistics_api, name='task_statistics_api'),
    path('projects/<int:project_id>/tasks/<int:task_id>/request-completion/', views.request_task_completion, name='request_task_completion'),
    path('projects/<int:project_id>/completion-requests/<int:request_id>/review/', views.review_task_completion, name='review_task_completion'),
    path('completion-requests/pending/', views.pending_completion_requests_view, name='pending_completion_requests'),
    path('api/completion-requests/pending/', views.pending_completion_requests_api, name='pending_completion_requests_api'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('api/notifications/', views.notifications_api, name='notifications_api'),
    path('api/notifications/<int:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('api/notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('api/notifications/unread-count/', views.unread_notifications_count, name='unread_notifications_count'),
    path('api/check-deadline-warnings/', views.check_deadline_warnings_manual, name='check_deadline_warnings_manual'),
]