from . import views
from django.urls import path

urlpatterns = [
    path('overview/', views.view_overview, name='view_overview'),
    path('projects/', views.view_projects, name='view_projects'),
    path('projects/create/', views.create_project, name='create_project'),
    path('projects/<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path('projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('projects/<int:project_id>/', views.view_project_detail, name='view_project_detail'),
    path('projects/<int:project_id>/tasks/create/', views.create_task, name='create_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.view_project_task_id, name='view_project_task_id'),
    path('projects/<int:project_id>/tasks/<int:task_id>/update/', views.update_task, name='update_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/comments/', views.create_comment, name='create_comment'),
    path('projects/<int:project_id>/members/', views.view_project_members, name='view_project_members'),
    path('projects/<int:project_id>/members/invite/', views.invite_member, name='invite_member'),
    path('projects/<int:project_id>/members/<int:member_id>/remove/', views.remove_member, name='remove_member'),
    path('projects/<int:project_id>/members/<int:member_id>/update-role/', views.update_member_role, name='update_member_role'),
    path('projects/<int:project_id>/invitations/<int:invitation_id>/cancel/', views.cancel_invitation, name='cancel_invitation'),
    path('invitations/<int:invitation_id>/accept/', views.accept_invitation, name='accept_invitation'),
    path('invitations/<int:invitation_id>/decline/', views.decline_invitation, name='decline_invitation'),
    path('members/', views.view_all_members, name='view_all_members'),
    path('frame/', views.view_frame, name='view_frame'),
    path('settings/', views.view_settings, name='view_settings'),
    path('personal/', views.view_profile, name='view_profile'),
    path('personal/update/', views.update_profile, name='update_profile'),
    path('personal/change-password/', views.change_password, name='change_password'),
    path('search/', views.search_view, name='search'),
]